### PR TITLE
fix #221

### LINKED ISSUE #221: formatter.addresses(address_mode::none) does not work
in cpptrace v0.8.2, it prints object address when `address_mode::none` is set.

https://github.com/jeremy-rifkin/cpptrace/blob/c37b5ed7364f4fc1c58e92d13399cd04656e6572/src/formatting.cpp#L213

### PR DESCRIPTION
**Pull request by Tsche**

### CODE REVIEW

File: test/unit/lib/formatting.cpp [hunk 1]
```diff
@@ -96,6 +96,21 @@ TEST(FormatterTest, ObjectAddresses) {
...
 
+TEST(FormatterTest, NoAddresses) {
+    auto formatter = cpptrace::formatter{}
+        .addresses(cpptrace::formatter::address_mode::none);
+    auto res = split(formatter.format(make_test_stacktrace()), "\n");
+    EXPECT_THAT(
+        res,
+        ElementsAre(
+            "Stack trace (most recent call first):",
+            "#0  in foo() at foo.cpp:20:30",
```
Comment (jeremy-rifkin) [inline test/unit/lib/formatting.cpp:107]: I think we'll want this to format as `#0 in foo() at foo.cpp:20:30`. This makes the change in formatting.cpp slightly more annoying but not too bad.
(This is also important for `cpptrace::stacktrace_frame::to_string` etc, at the moment that'll return ` in foo() at foo.cpp:20:30`)

**Review by jeremy-rifkin — COMMENTED** [review]
Thanks for the PR! One minor detail but otherwise straightforward.

**Review by jeremy-rifkin — APPROVED** [review]
Thanks! LGTM
